version: "3.7"

services:
  postgres:
    build:
      context: .
      dockerfile: src/Dockerfile.pg
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=vector-db
      - POSTGRES_USER=vector-db
      - POSTGRES_PASSWORD=vector-db
