version: "3.7"

services:

  vector-db:
    build:
      context: .
      dockerfile: src/Dockerfile.vector
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=vector-db
      - POSTGRES_USER=vector-db
      - POSTGRES_PASSWORD=vector-db

  api:
    build:
      context: .
      dockerfile: src/Dockerfile.api
    ports:
      - 8000:8000
    environment:
      - ENV_FOR_DYNACONF=compose
    depends_on:
      - vector-db
