version: "3.7"

services:

  db:
    build:
      context: .
      dockerfile: src/Dockerfile.db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=vector-db
      - POSTGRES_USER=vector-db
      - POSTGRES_PASSWORD=vector-db

  api:
    build:
      context: .
      dockerfile: src/Dockerfile.api
    ports:
      - 8000:8000
    environment:
      - ENV_FOR_DYNACONF=compose
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8000" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - db

  frontend:
    build:
      context: .
      secrets:
        - kaggle
      dockerfile: src/Dockerfile.frontend
    ports:
      - 8501:8501
    environment:
      - ENV_FOR_DYNACONF=compose
    restart: on-failure
    depends_on:
      - api
