[default.data]
dataset_name = "thedevastator/nike-usa-products-prices-descriptions-and-custom"

[default.embeddings]
model = "multi-qa-MiniLM-L6-cos-v1"

[development.db]
host = "localhost"
port = 5432
database = "vector-db"

[compose.db]
host = "vector-db"
port = 5432
database = "vector-db"
