FROM python:3.11.0-slim

WORKDIR /root

RUN pip install poetry

COPY poetry.lock .
COPY pyproject.toml .

RUN poetry config virtualenvs.create false
RUN poetry install --no-dev --no-root --only streamlit

# COPY src/config src/database src/embeddings src/graphql src/app.py src/__init__.py /root/src/
RUN --mount=type=secret,id=kaggle,target=/root/.kaggle/kaggle.json cat /root/.kaggle/kaggle.json
COPY src/ /root/src/
COPY settings.toml .
COPY .secrets.toml .

CMD streamlit run src/search.py
