FROM python:3.11.0-slim

WORKDIR /root

RUN pip install poetry

COPY poetry.lock .
COPY pyproject.toml .

RUN poetry config virtualenvs.create false
RUN poetry install --no-dev --no-root --only streamlit

COPY src/config ./src/config
COPY src/data ./src/data
COPY src/client ./src/client
COPY src/search.py ./src/

COPY settings.toml .
COPY .secrets.toml .

CMD streamlit run src/search.py
