name: Testing

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Poetry install
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Linting tests
        run: |
          black src/ --check
          flake8 src/
          isort src/ -c

      - name: Create secrets file
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_USERNAME }}
        run: |
          cat <<EOF > .secrets.toml
          dynaconf_merge=true

          [default.kaggle]
          username = "$KAGGLE_USERNAME"
          key = "$KAGGLE_KEY"

          [default.db]
          username = "vector-db"
          password = "vector-db"

          EOF

      - name: Test with pytest
        run: |
          python -m pytest tests --junitxml=junit/test-results.xml --cov=src --cov-report=xml --cov-report=html

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: junit/test-results.xml
        if: ${{ always() }}
